In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
houses = pd.read_csv('trains.csv')
holdout_set = pd.read_csv('test.csv')

In [3]:
houses.head()

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice
0,109,533352170,60,RL,NaN,13517,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,130500
1,544,531379050,60,RL,43.0,11492,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,4,2009,WD,220000
2,153,535304180,20,RL,68.0,7922,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,1,2010,WD,109000
3,318,916386060,60,RL,73.0,9802,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,4,2010,WD,174000
4,255,906425045,50,RL,82.0,14235,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,138500

In [4]:
features = ['Overall Qual', 'Year Built']
x= houses [features]
y = houses ['SalePrice']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(x,y)

In [6]:
from sklearn.model_selection import cross_val_score

In [7]:
x.isnull().sum()

Overall Qual    0
Year Built      0
dtype: int64

In [8]:
houses['Street'].value_counts()

Pave    2044
Grvl       7
Name: Street, dtype: int64

In [10]:
from sklearn.linear_model import Ridge

In [15]:
ridge=Ridge()

In [17]:
scores = cross_val_score(ridge, X_train, y_train)
print(scores)
print(scores.mean())

[0.6640537  0.67815623 0.63335756]
0.6585224945662181

In [18]:
ridge.fit(x,y)

Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001)

In [19]:
ridge.coef_

array([39748.70197317,   369.16160765])

In [20]:
holdout_set.head()

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type
0,2658,902301120,190,RM,69.0,9142,Pave,Grvl,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,4,2006,WD
1,2718,905108090,90,RL,NaN,9662,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,8,2006,WD
2,2414,528218130,60,RL,58.0,17104,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,9,2006,New
3,1989,902207150,30,RM,60.0,8520,Pave,NaN,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,7,2007,WD
4,625,535105100,20,RL,NaN,9500,Pave,NaN,IR1,Lvl,...,0,185,0,NaN,NaN,NaN,0,7,2009,WD

In [21]:
X_pred = pd.DataFrame(holdout_set[features])

In [23]:
y_preds =ridge.predict(X_pred)

y_preds

array([154231.70047463, 139216.82621427, 229419.91678257, 119282.09940096,
       173797.26568028,  97622.31620283,  92454.05369567, 139216.82621427,
       228681.59356726, 178965.52818744, 184133.79069459, 159769.12458944,
       170474.8112114 , 227204.94713664, 159399.96298178, 131833.59406119,
       165306.54870424, 131464.43245353, 173058.94246497, 223392.57940666,
       135894.37174538, 133310.2404918 , 184872.1139099 , 176012.2353262 ,
       229789.07839022, 137371.018176  ,  78425.91260482, 103408.15027184,
       173797.26568028,  47906.250823  ,  97253.15459517,  80271.72064309,
       182905.55421818, 137740.17978365, 227574.1087443 , 229419.91678257,
        78425.91260482,  87654.95279617, 130356.94763057, 226835.78552899,
       190778.69963236, 226466.62392134, 132571.9172765 , 129618.62441526,
       222405.84623714,  96883.99298752, 227574.1087443 , 134786.88692242,
       131464.43245353, 134048.56370711, 121866.23065453, 226345.87226789,
       269537.78036339, 124819.52351576, 119651.26100861, 176012.2353262 ,
       199517.82656261, 132202.75566884, 217975.9069453 , 227204.94713664,
       266215.32589451, 118174.614578  , 132202.75566884, 216499.26051468,
       184502.95230224, 264738.67946389,  97253.15459517, 189302.05320174,
        42737.98831585, 188932.89159409,  80640.88225075, 269537.78036339,
       172689.78085732, 223882.49266776, 137001.85656834, 175273.9121109 ,
       349035.18430973, 132941.07888415, 173428.10407263, 132571.9172765 ,
       308178.9975136 , 227943.27035195, 158292.47815882, 121866.23065453,
        74734.29652829, 186348.76034051, 269906.94197105, 137371.018176  ,
       176750.55854151, 259939.57856439, 168259.84156547, 133679.40209946,
        74734.29652829, 164568.22548894, 262523.70981797, 125188.68512342,
       160507.44780474, 131464.43245353, 269168.61875574, 187825.40677113,
       267322.81071747, 258462.93213378, 171582.29603436, 141800.95746784,
       347558.53787912, 171582.29603436, 127403.65476934, 184872.1139099 ,
       179334.68979509, 174166.42728794,  95776.50816456, 177858.04336447,
       266953.64910982,  89131.59922679, 149922.51283623, 226466.62392134,
       344605.24501789, 110791.38242492, 136632.69496069, 309655.64394422,
       186717.92194817, 349035.18430973, 269168.61875574, 308548.15912125,
       186348.76034051,  75472.61974359, 308548.15912125, 137371.018176  ,
       130356.94763057, 118174.614578  , 309286.48233656, 138847.66460661,
       186717.92194817, 135894.37174538, 174904.75050324, 187087.08355582,
       205424.41228507, 229789.07839022, 228681.59356726, 189302.05320174,
       141431.79586019, 177119.72014917, 129249.46280761, 152755.05404401,
       169736.48799609, 128141.97798465, 129987.78602292, 156077.5085129 ,
       178965.52818744,  78425.91260482, 220190.87659122, 228681.59356726,
       170474.8112114 , 157923.31655117, 135525.21013773, 119651.26100861,
       131095.27084588,  96883.99298752, 171582.29603436, 223882.49266776,
       267322.81071747, 186348.76034051, 127772.816377  , 130726.10923823,
       349035.18430973, 309655.64394422, 269537.78036339, 188563.72998644,
       229419.91678257, 229050.75517491, 228681.59356726, 344974.40662554,
       145492.57354438, 133679.40209946, 229050.75517491, 224989.97749072,
       173428.10407263, 118174.614578  , 139216.82621427,  96883.99298752,
       132941.07888415, 122235.39226219, 215391.77569172, 217606.74533764,
       229419.91678257, 177858.04336447, 164937.38709659, 228312.43195961,
       198410.34173964, 133679.40209946,  50490.38207658, 218345.06855295,
       137740.17978365, 157184.99333586, 134048.56370711, 189302.05320174,
       179334.68979509, 269537.78036339, 125188.68512342, 132202.75566884,
       131464.43245353, 266215.32589451, 193980.4024478 , 174166.42728794,
       184872.1139099 , 156077.5085129 ,  89500.76083444, 178596.36657978,
       173428.10407263, 269168.61875574, 190040.37641705, 187087.08355582,
       177858.04336447,  79533.39742779, 214284.29086876, 306333.18947533,
       224251.65427541, 215022.61408407, 207270.22032334,  79533.39742779,
       132571.9172765 , 226835.78552899, 180073.0130104 , 173797.26568028,
       189302.05320174, 164937.38709659, 118174.614578  , 267691.97232512,
       229419.91678257, 132941.07888415, 225728.30070603, 125557.84673107,
        97622.31620283,  71042.68045175,  91346.56887271, 236682.3972822 ,
       185610.4371252 , 120020.42261626, 309286.48233656, 268799.45714808,
       229419.91678257, 269168.61875574, 181549.65944101, 268061.13393278,
       228312.43195961, 309655.64394422, 269537.78036339, 171213.1344267 ,
        93192.37691098, 187456.24516347, 309286.48233656, 269168.61875574,
       165306.54870424, 265107.84107155, 228312.43195961, 183026.30587163,
        42368.82670819,  74734.29652829, 308548.15912125, 224620.81588307,
       171951.45764201, 228681.59356726, 169736.48799609, 177488.88175682,
       170105.64960374, 229419.91678257, 174166.42728794, 131833.59406119,
       224620.81588307, 174166.42728794, 189302.05320174, 154231.70047463,
       229419.91678257, 197672.01852434, 242958.14461231,  96883.99298752,
       136263.53335303, 188563.72998644, 139585.98782192, 129249.46280761,
       130726.10923823, 268799.45714808, 159769.12458944, 144385.08872142,
       110791.38242492, 165675.7103119 , 224989.97749072, 162353.25584301,
       177488.88175682, 160876.6094124 , 131464.43245353, 133310.2404918 ,
       178965.52818744,  99098.96263344, 133310.2404918 , 131464.43245353,
       188932.89159409, 229050.75517491, 225359.13909838, 268061.13393278,
       159030.80137413, 167521.51835017, 309655.64394422, 139216.82621427,
       119282.09940096, 125557.84673107, 132571.9172765 , 134786.88692242,
       229419.91678257, 139585.98782192, 134786.88692242, 129249.46280761,
       267322.81071747, 229419.91678257, 268430.29554043,  95776.50816456,
       310393.96715952, 310024.80555187, 265846.16428685, 226835.78552899,
       129249.46280761,  88393.27601148, 110791.38242492, 119651.26100861,
       270276.1035787 , 137371.018176  , 178596.36657978, 131833.59406119,
       229050.75517491, 208746.86675395, 128880.30119996, 132202.75566884,
       184133.79069459, 128511.1395923 , 259570.41695674, 115221.32171676,
       197672.01852434, 119282.09940096,  67351.06437521, 168259.84156547,
       259570.41695674, 139216.82621427, 114482.99850146, 128880.30119996,
       186717.92194817, 264000.35624858, 266953.64910982, 185979.59873286,
       135156.04853007, 228681.59356726, 135525.21013773, 191027.10958657,
       178596.36657978, 177119.72014917, 269168.61875574,  90977.40726506,
       215022.61408407, 154231.70047463, 226835.78552899, 266953.64910982,
       117805.45297034, 165675.7103119 ,  93561.53851863, 117067.12975503,
       132202.75566884, 269537.78036339, 269168.61875574, 134048.56370711,
       139216.82621427, 228312.43195961,  51597.86689954, 176012.2353262 ,
       177119.72014917, 157554.15494351, 306702.35108299, 174904.75050324,
       269168.61875574, 196933.69530903, 268430.29554043, 229789.07839022,
       141800.95746784, 156077.5085129 , 193980.4024478 , 309655.64394422,
       269168.61875574, 224989.97749072, 174904.75050324, 110791.38242492,
       239266.52853578, 133679.40209946, 128511.1395923 , 137001.85656834,
       229789.07839022, 180073.0130104 ,  89500.76083444, 230527.40160553,
        74734.29652829, 189671.2148094 , 186348.76034051, 141062.63425253,
        44214.63474646, 262523.70981797, 219452.55337591, 118543.77618565,
       269168.61875574, 132941.07888415, 133679.40209946, 114482.99850146,
       228312.43195961, 268799.45714808, 129618.62441526,  84701.65993494,
       131095.27084588, 219821.71498357, 131833.59406119, 265107.84107155,
       266215.32589451, 128511.1395923 , 223513.33106011,  97253.15459517,
       131833.59406119, 170474.8112114 , 131095.27084588, 123712.0386928 ,
       150540.08439809, 227574.1087443 , 349773.50752504, 259939.57856439,
       228312.43195961, 217975.9069453 , 307440.67429829,  89131.59922679,
       170474.8112114 , 128880.30119996, 228681.59356726,  74734.29652829,
       268799.45714808, 229050.75517491, 175643.07371855, 228312.43195961,
       175643.07371855, 224620.81588307, 135525.21013773, 165306.54870424,
       178965.52818744, 180073.0130104 , 135894.37174538,  -1071.49134152,
        80271.72064309, 225728.30070603, 137371.018176  , 214284.29086876,
       269537.78036339, 230527.40160553, 201732.79620853, 229050.75517491,
       267691.97232512, 226097.46231368, 131464.43245353, 264000.35624858,
       132571.9172765 , 180073.0130104 , 132202.75566884, 174904.75050324,
       344236.08341023,  76949.26617421, 228681.59356726, 224251.65427541,
       227574.1087443 , 181549.65944101, 141062.63425253, 141431.79586019,
       229050.75517491, 185241.27551755, 135894.37174538, 223513.33106011,
       267322.81071747, 129987.78602292, 136263.53335303, 118174.614578  ,
       189302.05320174,  92084.89208802, 226097.46231368, 136632.69496069,
       225728.30070603, 242588.98300466, 174535.58889559, 188932.89159409,
       178596.36657978, 190409.53802471, 160138.28619709, 107838.08956369,
       229419.91678257, 157184.99333586, 217237.58372999, 308548.15912125,
       228681.59356726, 116328.80653973, 120020.42261626, 136263.53335303,
        93192.37691098, 189302.05320174, 258093.77052612, 228681.59356726,
       184872.1139099 , 189671.2148094 , 139585.98782192, 241850.65978935,
       156446.67012055, 139216.82621427, 269168.61875574,  45322.11956942,
       137740.17978365, 136263.53335303, 134786.88692242,   8526.71045748,
       172320.61924967, 134417.72531477, 226097.46231368, 269906.94197105,
       263631.19464093, 120020.42261626, 124081.20030046, 110791.38242492,
       135525.21013773, 228312.43195961, 309286.48233656, 259570.41695674,
       134786.88692242, 120020.42261626,   6311.74081156, 218345.06855295,
       189671.2148094 , 177858.04336447, 230896.56321318, 125188.68512342,
       164199.06388128,  96883.99298752, 208746.86675395, 145492.57354438,
       187825.40677113, 176750.55854151,  96883.99298752,  96883.99298752,
       185979.59873286, 223144.16945245, 268430.29554043, 226466.62392134,
       129987.78602292, 177119.72014917, 269537.78036339, 120389.58422392,
       265846.16428685, 127403.65476934, 135525.21013773, 230158.23999788,
       121866.23065453, 141800.95746784, 178596.36657978, 157923.31655117,
       161614.9326277 , 137001.85656834, 229419.91678257, 185610.4371252 ,
       135525.21013773, 178965.52818744, 138478.50299896, 149184.18962092,
       190409.53802471, 170474.8112114 , 196933.69530903, 147338.38158265,
       131464.43245353,  92823.21530333, 146230.89675969, 171951.45764201,
       160138.28619709, 176750.55854151, 188932.89159409, 118174.614578  ,
       114482.99850146, 118912.9377933 , 136263.53335303, 229050.75517491,
       118912.9377933 , 174166.42728794, 171951.45764201, 133310.2404918 ,
        93561.53851863, 269537.78036339, 227943.27035195, 114482.99850146,
       137001.85656834, 133310.2404918 , 125557.84673107, 308917.32072891,
       217606.74533764, 112637.19046319, 141062.63425253, 134048.56370711,
       308917.32072891, 121866.23065453, 227574.1087443 , 138109.3413913 ,
       178596.36657978, 229419.91678257, 120389.58422392, 131095.27084588,
        96883.99298752, 190778.69963236, 124819.52351576, 124819.52351576,
       269168.61875574, 226097.46231368, 129618.62441526, 168259.84156547,
         4835.09438095, 229789.07839022, 266584.48750216,  91346.56887271,
       227204.94713664, 229789.07839022, 139955.14942957, 129249.46280761,
       135894.37174538, 156077.5085129 , 139216.82621427, 229789.07839022,
       132941.07888415, 268430.29554043, 189302.05320174, 129249.46280761,
       157554.15494351, 137371.018176  ,  36462.24098573, 149922.51283623,
       187456.24516347, 188932.89159409, 178596.36657978, 132941.07888415,
       112268.02885553, 309286.48233656, 141062.63425253, 189302.05320174,
       269537.78036339, 176012.2353262 ,  80271.72064309, 267691.97232512,
       226835.78552899, 189302.05320174, 187087.08355582, 132941.07888415,
       130726.10923823, 118912.9377933 , 176012.2353262 ,  49382.89725362,
       156077.5085129 , 228312.43195961, 154231.70047463, 224989.97749072,
       173428.10407263, 179334.68979509, 181549.65944101, 175643.07371855,
       218714.23016061, 308917.32072891, 229050.75517491, 129987.78602292,
       161614.9326277 , 132941.07888415, 268430.29554043, 269537.78036339,
       228681.59356726, 223882.49266776, 123712.0386928 , 144754.25032907,
       130726.10923823, 128880.30119996,  97991.47781048, 157923.31655117,
       137371.018176  , 265846.16428685, 216868.42212234, 187087.08355582,
       269168.61875574, 184872.1139099 , 176750.55854151, 185241.27551755,
       308548.15912125, 130726.10923823, 186348.76034051,  52705.3517225 ,
       135156.04853007, 229050.75517491, 157923.31655117, 222036.68462949,
       181549.65944101, 230527.40160553, 268799.45714808, 138478.50299896,
       268061.13393278, 188932.89159409, 109804.6492554 , 180442.17461805,
       133310.2404918 , 219821.71498357, 215391.77569172, 178596.36657978,
       130726.10923823,  91346.56887271, 308548.15912125, 228312.43195961,
        78425.91260482, 129618.62441526, 136263.53335303, 125927.00833873,
       153493.37725932, 223144.16945245, 266584.48750216, 170843.97281905,
       205424.41228507, 228681.59356726, 268061.13393278, 139216.82621427,
       137371.018176  , 266953.64910982, 148445.86640561, 218714.23016061,
       128141.97798465, 268430.29554043,  71042.68045175, 270276.1035787 ,
       187456.24516347, 268061.13393278, 178965.52818744, 131833.59406119,
       145123.41193673, 127772.816377  , 177119.72014917, 173797.26568028,
       132571.9172765 , 227943.27035195, 138847.66460661, 131833.59406119,
       118174.614578  , 184872.1139099 , 131464.43245353, 226097.46231368,
       176381.39693386, 160138.28619709, 268799.45714808, 269906.94197105,
       128511.1395923 , 179334.68979509, 174166.42728794,  94299.86173394,
       177488.88175682, 309286.48233656,  74734.29652829, 149553.35122857,
       269168.61875574, 178965.52818744, 226097.46231368,  94299.86173394,
       171582.29603436, 154231.70047463, 268799.45714808, 225728.30070603,
       229050.75517491, 268061.13393278, 184872.1139099 , 225728.30070603,
       212069.32122284, 134417.72531477, 176381.39693386, 124819.52351576,
       134786.88692242, 230158.23999788, 172689.78085732,  90977.40726506,
       119282.09940096, 187456.24516347, 308548.15912125, 118174.614578  ,
       137371.018176  ,  88024.11440383, 130726.10923823, 269537.78036339,
       180073.0130104 , 228312.43195961, 132571.9172765 , 217606.74533764,
       227943.27035195, 181918.82104867, 264369.51785624, 132571.9172765 ,
       258832.09374143, 262523.70981797, 230527.40160553, 229419.91678257,
       219452.55337591, 132202.75566884, 161614.9326277 , 226835.78552899,
        73626.81170532, 229419.91678257, 120020.42261626, 119651.26100861,
       229050.75517491, 160138.28619709, 132202.75566884, 131464.43245353,
       264738.67946389, 179334.68979509, 133679.40209946, 229789.07839022,
       229789.07839022, 170474.8112114 ,  65505.25633694,  95038.18494925,
       182287.98265632, 175643.07371855, 135156.04853007, 304118.21982941,
        71042.68045175, 226835.78552899, 223513.33106011, 308917.32072891,
       132941.07888415, 178596.36657978, 135156.04853007, 229050.75517491,
       172689.78085732, 267691.97232512, 269168.61875574, 169367.32638844,
       134048.56370711, 268799.45714808, 130356.94763057, 136263.53335303,
       135156.04853007, 217606.74533764, 228312.43195961, 219452.55337591,
       135525.21013773, 186348.76034051, 175643.07371855, 216130.09890703,
       230527.40160553, 180073.0130104 , 179334.68979509, 186717.92194817,
       175273.9121109 , 172320.61924967, 139955.14942957, 157184.99333586,
        36831.40259339, 266215.32589451,  96883.99298752, 228312.43195961,
       142170.1190755 , 307809.83590595, 226466.62392134, 136632.69496069,
       133310.2404918 , 139955.14942957, 227943.27035195, 185979.59873286,
       221298.36141418, 142170.1190755 , 134417.72531477, 228681.59356726,
       269906.94197105, 228312.43195961, 177858.04336447, 174904.75050324,
       135894.37174538,  97253.15459517, 131095.27084588])

In [24]:
pd.read_csv('sample_sub_reg.csv', index_col='Id')

        SalePrice
Id
2     181479.1217
4     181479.1217
6     181479.1217
7     181479.1217
17    181479.1217
18    181479.1217
22    181479.1217
27    181479.1217
31    181479.1217
36    181479.1217
39    181479.1217
40    181479.1217
42    181479.1217
46    181479.1217
53    181479.1217
58    181479.1217
61    181479.1217
72    181479.1217
79    181479.1217
80    181479.1217
82    181479.1217
83    181479.1217
85    181479.1217
88    181479.1217
92    181479.1217
93    181479.1217
95    181479.1217
102   181479.1217
103   181479.1217
106   181479.1217
...           ...
2825  181479.1217
2828  181479.1217
2831  181479.1217
2843  181479.1217
2845  181479.1217
2847  181479.1217
2855  181479.1217
2856  181479.1217
2859  181479.1217
2865  181479.1217
2867  181479.1217
2869  181479.1217
2870  181479.1217
2874  181479.1217
2876  181479.1217
2889  181479.1217
2892  181479.1217
2895  181479.1217
2898  181479.1217
2901  181479.1217
2902  181479.1217
2908  181479.1217
2909  181479.1217
2916  181479.1217
2917  181479.1217
2919  181479.1217
2921  181479.1217
2922  181479.1217
2925  181479.1217
2928  181479.1217

[879 rows x 1 columns]

In [25]:
df= pd.DataFrame()

In [26]:
myids= holdout_set['Id']

In [27]:
df['Id']=myids

In [28]:
df.head()

     Id
0  2658
1  2718
2  2414
3  1989
4   625

In [29]:
df['SalePrice']=y_preds

In [30]:
df

       Id      SalePrice
0    2658  154231.700475
1    2718  139216.826214
2    2414  229419.916783
3    1989  119282.099401
4     625  173797.265680
5     333   97622.316203
6    1327   92454.053696
7     858  139216.826214
8      95  228681.593567
9    1568  178965.528187
10   2482  184133.790695
11   1364  159769.124589
12   2584  170474.811211
13    818  227204.947137
14   2673  159399.962982
15   2089  131833.594061
16   1297  165306.548704
17    790  131464.432454
18   2616  173058.942465
19    720  223392.579407
20    222  135894.371745
21    557  133310.240492
22   1148  184872.113910
23   2766  176012.235326
24    534  229789.078390
25   1452  137371.018176
26    630   78425.912605
27   2648  103408.150272
28    125  173797.265680
29   1904   47906.250823
..    ...            ...
849   933  180073.013010
850  2784  179334.689795
851   972  186717.921948
852   599  175273.912111
853  2614  172320.619250
854  2582  139955.149430
855  1409  157184.993336
856   175   36831.402593
857   352  266215.325895
858   976   96883.992988
859  2134  228312.431960
860   984  142170.119075
861  2396  307809.835906
862  1673  226466.623921
863   404  136632.694961
864   607  133310.240492
865   814  139955.149430
866   868  227943.270352
867  2271  185979.598733
868  1633  221298.361414
869   337  142170.119075
870  2765  134417.725315
871  1746  228681.593567
872   368  269906.941971
873  2806  228312.431960
874  1662  177858.043364
875  1234  174904.750503
876  1373  135894.371745
877  1672   97253.154595
878  1939  131095.270846

[879 rows x 2 columns]

In [31]:
df.set_index('Id', inplace= True)

In [32]:
df.to_csv('./my_preds4.csv')