In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
houses = pd.read_csv('trains.csv')
holdout_set = pd.read_csv('test.csv')

In [3]:
houses.head()

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,SalePrice
0,109,533352170,60,RL,NaN,13517,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,130500
1,544,531379050,60,RL,43.0,11492,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,4,2009,WD,220000
2,153,535304180,20,RL,68.0,7922,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,1,2010,WD,109000
3,318,916386060,60,RL,73.0,9802,Pave,NaN,Reg,Lvl,...,0,0,NaN,NaN,NaN,0,4,2010,WD,174000
4,255,906425045,50,RL,82.0,14235,Pave,NaN,IR1,Lvl,...,0,0,NaN,NaN,NaN,0,3,2010,WD,138500

In [4]:
features = ['Overall Qual', 'Year Built']
x= houses [features]
y = houses ['SalePrice']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(x,y)

In [6]:
from sklearn.model_selection import cross_val_score

In [7]:
x.isnull().sum()

Overall Qual    0
Year Built      0
dtype: int64

In [8]:
houses['Street'].value_counts()

Pave    2044
Grvl       7
Name: Street, dtype: int64

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
linereg = LinearRegression()

In [11]:
scores = cross_val_score(linereg, X_train, y_train)
print(scores)
print(scores.mean())

[0.70395478 0.64621091 0.61091207]
0.6536925837951858

In [12]:
linereg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [13]:
linereg.coef_

array([39763.67454092,   368.73512724])

In [14]:
#X_pred.head()

In [16]:
holdout_set.head()

,Id,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type
0,2658,902301120,190,RM,69.0,9142,Pave,Grvl,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,4,2006,WD
1,2718,905108090,90,RL,NaN,9662,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,8,2006,WD
2,2414,528218130,60,RL,58.0,17104,Pave,NaN,IR1,Lvl,...,0,0,0,NaN,NaN,NaN,0,9,2006,New
3,1989,902207150,30,RM,60.0,8520,Pave,NaN,Reg,Lvl,...,0,0,0,NaN,NaN,NaN,0,7,2007,WD
4,625,535105100,20,RL,NaN,9500,Pave,NaN,IR1,Lvl,...,0,185,0,NaN,NaN,NaN,0,7,2009,WD

In [23]:
X_pred = pd.DataFrame(holdout_set[features])

In [24]:
y_preds =linereg.predict(X_pred)

y_preds

array([154256.3390916 , 139197.91807554, 229418.58584724, 119286.22120476,
       173799.30083515,  97590.56789844,  92428.27611713, 139197.91807554,
       228681.11559277, 178961.59261646, 184123.88439778, 159787.36600015,
       170480.68469002, 227206.17508382, 159418.63087292, 131823.21553081,
       165318.3929087 , 131454.48040357, 173061.83058067, 223459.10461081,
       135879.30193041, 133298.15603976, 184861.35465225, 176011.71159857,
       229787.32097448, 137354.24243936,  78416.34128214, 103430.61073358,
       173799.30083515,  47871.04492214,  97221.83277121,  80260.01691832,
       182957.95981542, 137722.9775666 , 227574.91021106, 229418.58584724,
        78416.34128214,  87634.71946305, 130348.27502186, 226837.43995659,
       190761.11668804, 226468.70482935, 132560.68578528, 129610.80476739,
       222412.61842975,  96853.09764397, 227574.91021106, 134773.0965487 ,
       131454.48040357, 134035.62629423, 121867.36709542, 226408.9856287 ,
       269550.9955154 , 124817.24811331, 119654.956332  , 176011.71159857,
       199551.04054107, 132191.95065805, 217987.7969029 , 227206.17508382,
       266232.37937027, 118180.01582305, 132191.95065805, 216512.85639396,
       184492.61952501, 264757.43886132,  97221.83277121, 189286.17617909,
        42708.75314082, 188917.44105185,  80628.75204556, 269550.9955154 ,
       172693.09545344, 223887.55893869, 136985.50731212, 175274.24134409,
       349078.34459723, 132929.42091252, 173430.56570791, 132560.68578528,
       308208.4646746 , 227943.6453383 , 158312.42549121, 121867.36709542,
        74728.99000977, 186336.2951612 , 269919.73064263, 137354.24243936,
       176749.18185304, 259963.88220724, 168268.2739266 , 133666.89116699,
        74728.99000977, 164580.92265423, 262545.0280979 , 125185.98324055,
       160524.83625463, 131454.48040357, 269182.26038816, 187811.23567014,
       267338.58475198, 258488.94169829, 171586.89007173, 141779.0639662 ,
       347603.40408828, 171586.89007173, 127398.39400397, 184861.35465225,
       179330.3277437 , 174168.03596238,  95746.89226226, 177855.38723475,
       266969.84962474,  89109.659972  , 149891.23676541, 226468.70482935,
       344653.52307039, 110805.31327832, 136616.77218489, 309683.40518355,
       186705.03028843, 349078.34459723, 269182.26038816, 308577.19980184,
       186336.2951612 ,  75466.46026424, 308577.19980184, 137354.24243936,
       130348.27502186, 118180.01582305, 309314.67005631, 138829.18294831,
       186705.03028843, 135879.30193041, 174905.50621686, 187073.76541567,
       205450.80257686, 229787.32097448, 228681.11559277, 189286.17617909,
       141410.32883896, 177117.91698028, 129242.06964015, 152781.39858265,
       169743.21443554, 128135.86425844, 129979.53989463, 156100.01472779,
       178961.59261646,  78416.34128214, 220200.20766632, 228681.11559277,
       170480.68469002, 157943.69036397, 135510.56680318, 119654.956332  ,
       131085.74527634,  96853.09764397, 171586.89007173, 223887.55893869,
       267338.58475198, 186336.2951612 , 127767.12913121, 130717.0101491 ,
       349078.34459723, 309683.40518355, 269550.9955154 , 188548.70592462,
       229418.58584724, 229049.85072001, 228681.11559277, 345022.25819763,
       145466.41523857, 133666.89116699, 229049.85072001, 224993.7643204 ,
       173430.56570791, 118180.01582305, 139197.91807554,  96853.09764397,
       132929.42091252, 122236.10222266, 215406.65101225, 217619.06177567,
       229418.58584724, 177855.38723475, 164949.65778147, 228312.38046553,
       198444.83515936, 133666.89116699,  50452.19081279, 218356.53203014,
       137722.9775666 , 157206.2201095 , 134035.62629423, 189286.17617909,
       179330.3277437 , 269550.9955154 , 125185.98324055, 132191.95065805,
       131454.48040357, 266232.37937027, 194020.01363252, 174168.03596238,
       184861.35465225, 156100.01472779,  89478.39509924, 178592.85748922,
       173430.56570791, 269182.26038816, 190023.64643356, 187073.76541567,
       177855.38723475,  79522.54666385, 214300.44563054, 306364.78903842,
       224256.29406593, 215037.91588501, 207294.47821304,  79522.54666385,
       132560.68578528, 226837.43995659, 180067.79799817, 173799.30083515,
       189286.17617909, 164949.65778147, 118180.01582305, 267707.31987921,
       229418.58584724, 132929.42091252, 225731.23457488, 125554.71836779,
        97590.56789844,  71041.6387374 ,  91322.07073542, 236733.56919133,
       185598.82490672, 120023.69145924, 309314.67005631, 268813.52526092,
       229418.58584724, 269182.26038816, 181542.73850712, 268076.05500645,
       228312.38046553, 309683.40518355, 269550.9955154 , 171218.15494449,
        93165.7463716 , 187442.50054291, 309314.67005631, 269182.26038816,
       165318.3929087 , 265126.17398856, 228312.38046553, 183017.67901607,
        42340.01801359,  74728.99000977, 308577.19980184, 224625.02919317,
       171955.62519896, 228681.11559277, 169743.21443554, 177486.65210751,
       170111.94956278, 229418.58584724, 174168.03596238, 131823.21553081,
       224625.02919317, 174168.03596238, 189286.17617909, 154256.3390916 ,
       229418.58584724, 197707.36490489, 243002.06635435,  96853.09764397,
       136248.03705765, 188548.70592462, 139566.65320278, 129242.06964015,
       130717.0101491 , 268813.52526092, 159787.36600015, 144360.20985686,
       110805.31327832, 165687.12803594, 224993.7643204 , 162368.51189081,
       177486.65210751, 160893.57138186, 131454.48040357, 133298.15603976,
       178961.59261646,  99065.50840739, 133298.15603976, 131454.48040357,
       188917.44105185, 229049.85072001, 225362.49944764, 268076.05500645,
       159049.89574568, 167530.80367212, 309683.40518355, 139197.91807554,
       119286.22120476, 125554.71836779, 132560.68578528, 134773.0965487 ,
       229418.58584724, 139566.65320278, 134773.0965487 , 129242.06964015,
       267338.58475198, 229418.58584724, 268444.79013369,  95746.89226226,
       310420.87543802, 310052.14031079, 265863.64424303, 226837.43995659,
       129242.06964015,  88372.18971753, 110805.31327832, 119654.956332  ,
       270288.46576987, 137354.24243936, 178592.85748922, 131823.21553081,
       229049.85072001, 208769.41872199, 128873.33451292, 132191.95065805,
       184123.88439778, 128504.59938568, 259595.14708   , 115230.13480516,
       197707.36490489, 119286.22120476,  67354.28746503, 168268.2739266 ,
       259595.14708   , 139197.91807554, 114492.66455069, 128873.33451292,
       186705.03028843, 264019.96860685, 266969.84962474, 185967.56003396,
       135141.83167594, 228681.11559277, 135510.56680318, 191070.13261462,
       178592.85748922, 177117.91698028, 269182.26038816,  90953.33560818,
       215037.91588501, 154256.3390916 , 226837.43995659, 266969.84962474,
       117811.28069582, 165687.12803594,  93534.48149884, 117073.81044134,
       132191.95065805, 269550.9955154 , 269182.26038816, 134035.62629423,
       139197.91807554, 228312.38046553,  51558.3961945 , 176011.71159857,
       177117.91698028, 157574.95523673, 306733.52416566, 174905.50621686,
       269182.26038816, 196969.89465041, 268444.79013369, 229787.32097448,
       141779.0639662 , 156100.01472779, 194020.01363252, 309683.40518355,
       269182.26038816, 224993.7643204 , 174905.50621686, 110805.31327832,
       239314.71508199, 133666.89116699, 128504.59938568, 136985.50731212,
       229787.32097448, 180067.79799817,  89478.39509924, 230524.79122895,
        74728.99000977, 189654.91130633, 186336.2951612 , 141041.59371173,
        44183.69364977, 262545.0280979 , 219462.73741185, 118548.75095029,
       269182.26038816, 132929.42091252, 133666.89116699, 114492.66455069,
       228312.38046553, 268813.52526092, 129610.80476739,  84684.83844516,
       131085.74527634, 219831.47253909, 131823.21553081, 265126.17398856,
       266232.37937027, 128504.59938568, 223518.82381146,  97221.83277121,
       131823.21553081, 170480.68469002, 131085.74527634, 123711.0427316 ,
       150568.98781923, 227574.91021106, 349815.8148517 , 259963.88220724,
       228312.38046553, 217987.7969029 , 307470.99442013,  89109.659972  ,
       170480.68469002, 128873.33451292, 228681.11559277,  74728.99000977,
       268813.52526092, 229049.85072001, 175642.97647133, 228312.38046553,
       175642.97647133, 224625.02919317, 135510.56680318, 165318.3929087 ,
       178961.59261646, 180067.79799817, 135879.30193041,  -1111.0077997 ,
        80260.01691832, 225731.23457488, 137354.24243936, 214300.44563054,
       269550.9955154 , 230524.79122895, 201763.45130449, 229049.85072001,
       267707.31987921, 226099.96970211, 131454.48040357, 264019.96860685,
       132560.68578528, 180067.79799817, 132191.95065805, 174905.50621686,
       344284.78794315,  76941.40077319, 228681.11559277, 224256.29406593,
       227574.91021106, 181542.73850712, 141041.59371173, 141410.32883896,
       229049.85072001, 185230.08977949, 135879.30193041, 223518.82381146,
       267338.58475198, 129979.53989463, 136248.03705765, 118180.01582305,
       189286.17617909,  92059.54098989, 226099.96970211, 136616.77218489,
       225731.23457488, 242633.33122712, 174536.77108962, 188917.44105185,
       178592.85748922, 190392.3815608 , 160156.10112739, 107855.43226042,
       229418.58584724, 157206.2201095 , 217250.32664843, 308577.19980184,
       228681.11559277, 116336.34018687, 120023.69145924, 136248.03705765,
        93165.7463716 , 189286.17617909, 258120.20657106, 228681.11559277,
       184861.35465225, 189654.91130633, 139566.65320278, 241895.86097264,
       156468.74985502, 139197.91807554, 269182.26038816,  45289.89903148,
       137722.9775666 , 136248.03705765, 134773.0965487 ,   8476.10550846,
       172324.3603262 , 134404.36142147, 226099.96970211, 269919.73064263,
       263651.23347961, 120023.69145924, 124079.77785884, 110805.31327832,
       135510.56680318, 228312.38046553, 309314.67005631, 259595.14708   ,
       134773.0965487 , 120023.69145924,   6263.69474504, 218356.53203014,
       189654.91130633, 177855.38723475, 230893.52635619, 125185.98324055,
       164212.18752699,  96853.09764397, 208769.41872199, 145466.41523857,
       187811.23567014, 176749.18185304,  96853.09764397,  96853.09764397,
       185967.56003396, 223150.08868422, 268444.79013369, 226468.70482935,
       129979.53989463, 177117.91698028, 269550.9955154 , 120392.42658647,
       265863.64424303, 127398.39400397, 135510.56680318, 230156.05610172,
       121867.36709542, 141779.0639662 , 178592.85748922, 157943.69036397,
       161631.04163634, 136985.50731212, 229418.58584724, 185598.82490672,
       135510.56680318, 178961.59261646, 138460.44782107, 149153.76651094,
       190392.3815608 , 170480.68469002, 196969.89465041, 147310.09087475,
       131454.48040357,  92797.01124437, 146203.88549304, 171955.62519896,
       160156.10112739, 176749.18185304, 188917.44105185, 118180.01582305,
       114492.66455069, 118917.48607753, 136248.03705765, 229049.85072001,
       118917.48607753, 174168.03596238, 171955.62519896, 133298.15603976,
        93534.48149884, 269550.9955154 , 227943.6453383 , 114492.66455069,
       136985.50731212, 133298.15603976, 125554.71836779, 308945.93492908,
       217619.06177567, 112648.9889145 , 141041.59371173, 134035.62629423,
       308945.93492908, 121867.36709542, 227574.91021106, 138091.71269383,
       178592.85748922, 229418.58584724, 120392.42658647, 131085.74527634,
        96853.09764397, 190761.11668804, 124817.24811331, 124817.24811331,
       269182.26038816, 226099.96970211, 129610.80476739, 168268.2739266 ,
         4788.75423609, 229787.32097448, 266601.1144975 ,  91322.07073542,
       227206.17508382, 229787.32097448, 139935.38833002, 129242.06964015,
       135879.30193041, 156100.01472779, 139197.91807554, 229787.32097448,
       132929.42091252, 268444.79013369, 189286.17617909, 129242.06964015,
       157574.95523673, 137354.24243936,  36440.2559778 , 149891.23676541,
       187442.50054291, 188917.44105185, 178592.85748922, 132929.42091252,
       112280.25378726, 309314.67005631, 141041.59371173, 189286.17617909,
       269550.9955154 , 176011.71159857,  80260.01691832, 267707.31987921,
       226837.43995659, 189286.17617909, 187073.76541567, 132929.42091252,
       130717.0101491 , 118917.48607753, 176011.71159857,  49345.98543108,
       156100.01472779, 228312.38046553, 154256.3390916 , 224993.7643204 ,
       173430.56570791, 179330.3277437 , 181542.73850712, 175642.97647133,
       218725.26715738, 308945.93492908, 229049.85072001, 129979.53989463,
       161631.04163634, 132929.42091252, 268444.79013369, 269550.9955154 ,
       228681.11559277, 223887.55893869, 123711.0427316 , 144728.9449841 ,
       130717.0101491 , 128873.33451292,  97959.30302568, 157943.69036397,
       137354.24243936, 265863.64424303, 216881.59152119, 187073.76541567,
       269182.26038816, 184861.35465225, 176749.18185304, 185230.08977949,
       308577.19980184, 130717.0101491 , 186336.2951612 ,  52664.60157621,
       135141.83167594, 229049.85072001, 157943.69036397, 222043.88330251,
       181542.73850712, 230524.79122895, 268813.52526092, 138460.44782107,
       268076.05500645, 188917.44105185, 109758.82709726, 180436.53312541,
       133298.15603976, 219831.47253909, 215406.65101225, 178592.85748922,
       130717.0101491 ,  91322.07073542, 308577.19980184, 228312.38046553,
        78416.34128214, 129610.80476739, 136248.03705765, 125923.45349502,
       153518.86883713, 223150.08868422, 266601.1144975 , 170849.41981725,
       205450.80257686, 228681.11559277, 268076.05500645, 139197.91807554,
       137354.24243936, 266969.84962474, 148416.29625646, 218725.26715738,
       128135.86425844, 268444.79013369,  71041.6387374 , 270288.46576987,
       187442.50054291, 268076.05500645, 178961.59261646, 131823.21553081,
       145097.68011133, 127767.12913121, 177117.91698028, 173799.30083515,
       132560.68578528, 227943.6453383 , 138829.18294831, 131823.21553081,
       118180.01582305, 184861.35465225, 131454.48040357, 226099.96970211,
       176380.4467258 , 160156.10112739, 268813.52526092, 269919.73064263,
       128504.59938568, 179330.3277437 , 174168.03596238,  94271.95175331,
       177486.65210751, 309314.67005631,  74728.99000977, 149522.50163817,
       269182.26038816, 178961.59261646, 226099.96970211,  94271.95175331,
       171586.89007173, 154256.3390916 , 268813.52526092, 225731.23457488,
       229049.85072001, 268076.05500645, 184861.35465225, 225731.23457488,
       212088.03486712, 134404.36142147, 176380.4467258 , 124817.24811331,
       134773.0965487 , 230156.05610172, 172693.09545344,  90953.33560818,
       119286.22120476, 187442.50054291, 308577.19980184, 118180.01582305,
       137354.24243936,  88003.45459029, 130717.0101491 , 269550.9955154 ,
       180067.79799817, 228312.38046553, 132560.68578528, 217619.06177567,
       227943.6453383 , 181911.47363435, 264388.70373408, 132560.68578528,
       258857.67682553, 262545.0280979 , 230524.79122895, 229418.58584724,
       219462.73741185, 132191.95065805, 161631.04163634, 226837.43995659,
        73622.78462806, 229418.58584724, 120023.69145924, 119654.956332  ,
       229049.85072001, 160156.10112739, 132191.95065805, 131454.48040357,
       264757.43886132, 179330.3277437 , 133666.89116699, 229787.32097448,
       229787.32097448, 170480.68469002,  65510.61182885,  95009.42200779,
       182280.20876159, 175642.97647133, 135141.83167594, 304152.378275  ,
        71041.6387374 , 226837.43995659, 223518.82381146, 308945.93492908,
       132929.42091252, 178592.85748922, 135141.83167594, 229049.85072001,
       172693.09545344, 267707.31987921, 269182.26038816, 169374.47930831,
       134035.62629423, 268813.52526092, 130348.27502186, 136248.03705765,
       135141.83167594, 217619.06177567, 228312.38046553, 219462.73741185,
       135510.56680318, 186336.2951612 , 175642.97647133, 216144.12126672,
       230524.79122895, 180067.79799817, 179330.3277437 , 186705.03028843,
       175274.24134409, 172324.3603262 , 139935.38833002, 157206.2201095 ,
        36808.99110504, 266232.37937027,  96853.09764397, 228312.38046553,
       142147.79909344, 307839.72954737, 226468.70482935, 136616.77218489,
       133298.15603976, 139935.38833002, 227943.6453383 , 185967.56003396,
       221306.41304803, 142147.79909344, 134404.36142147, 228681.11559277,
       269919.73064263, 228312.38046553, 177855.38723475, 174905.50621686,
       135879.30193041,  97221.83277121, 131085.74527634])

In [25]:
pd.read_csv('sample_sub_reg.csv', index_col='Id')

        SalePrice
Id
2     181479.1217
4     181479.1217
6     181479.1217
7     181479.1217
17    181479.1217
18    181479.1217
22    181479.1217
27    181479.1217
31    181479.1217
36    181479.1217
39    181479.1217
40    181479.1217
42    181479.1217
46    181479.1217
53    181479.1217
58    181479.1217
61    181479.1217
72    181479.1217
79    181479.1217
80    181479.1217
82    181479.1217
83    181479.1217
85    181479.1217
88    181479.1217
92    181479.1217
93    181479.1217
95    181479.1217
102   181479.1217
103   181479.1217
106   181479.1217
...           ...
2825  181479.1217
2828  181479.1217
2831  181479.1217
2843  181479.1217
2845  181479.1217
2847  181479.1217
2855  181479.1217
2856  181479.1217
2859  181479.1217
2865  181479.1217
2867  181479.1217
2869  181479.1217
2870  181479.1217
2874  181479.1217
2876  181479.1217
2889  181479.1217
2892  181479.1217
2895  181479.1217
2898  181479.1217
2901  181479.1217
2902  181479.1217
2908  181479.1217
2909  181479.1217
2916  181479.1217
2917  181479.1217
2919  181479.1217
2921  181479.1217
2922  181479.1217
2925  181479.1217
2928  181479.1217

[879 rows x 1 columns]

In [26]:
df= pd.DataFrame()

In [27]:
myids= holdout_set['Id']

In [28]:
df['Id']=myids

In [29]:
df.head()

     Id
0  2658
1  2718
2  2414
3  1989
4   625

In [30]:
df['SalePrice']=y_preds

In [31]:
df

       Id      SalePrice
0    2658  154256.339092
1    2718  139197.918076
2    2414  229418.585847
3    1989  119286.221205
4     625  173799.300835
5     333   97590.567898
6    1327   92428.276117
7     858  139197.918076
8      95  228681.115593
9    1568  178961.592616
10   2482  184123.884398
11   1364  159787.366000
12   2584  170480.684690
13    818  227206.175084
14   2673  159418.630873
15   2089  131823.215531
16   1297  165318.392909
17    790  131454.480404
18   2616  173061.830581
19    720  223459.104611
20    222  135879.301930
21    557  133298.156040
22   1148  184861.354652
23   2766  176011.711599
24    534  229787.320974
25   1452  137354.242439
26    630   78416.341282
27   2648  103430.610734
28    125  173799.300835
29   1904   47871.044922
..    ...            ...
849   933  180067.797998
850  2784  179330.327744
851   972  186705.030288
852   599  175274.241344
853  2614  172324.360326
854  2582  139935.388330
855  1409  157206.220109
856   175   36808.991105
857   352  266232.379370
858   976   96853.097644
859  2134  228312.380466
860   984  142147.799093
861  2396  307839.729547
862  1673  226468.704829
863   404  136616.772185
864   607  133298.156040
865   814  139935.388330
866   868  227943.645338
867  2271  185967.560034
868  1633  221306.413048
869   337  142147.799093
870  2765  134404.361421
871  1746  228681.115593
872   368  269919.730643
873  2806  228312.380466
874  1662  177855.387235
875  1234  174905.506217
876  1373  135879.301930
877  1672   97221.832771
878  1939  131085.745276

[879 rows x 2 columns]

In [32]:
df.set_index('Id', inplace= True)

In [33]:
df.to_csv('./my_preds3.csv')